# Generated by Django 4.0.4 on 2022-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(db_column='userid', max_length=20)),
                ('userpw', models.CharField(db_column='userpw', max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
