# Generated by Django 4.1 on 2022-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NLP_models',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=45)),
                ('model_task', models.CharField(max_length=45)),
                ('epoch', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('learning_rate', models.FloatField(max_length=45)),
                ('accuracy', models.FloatField(max_length=45)),
                ('f1', models.FloatField(max_length=45)),
                ('speed', models.FloatField(max_length=45)),
                ('volume', models.FloatField(max_length=45)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='ex) pretrained-model, used data-set etc...')),
            ],
            options={
                'db_table': 'NLP_Models',
            },
        ),
    ]
