# Generated by Django 4.1 on 2022-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_nlp_models_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nlp_models',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
