# Generated by Django 4.1.3 on 2022-11-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_nlp_models_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nlp_models',
            old_name='accuracy',
            new_name='precision',
        ),
        migrations.RenameField(
            model_name='nlp_models',
            old_name='speed',
            new_name='recall',
        ),
    ]
